### ISSUE TITLE
Payslip Deductions

### ISSUE THREAD

**Issue by loanduong02** [horilla-opensource/horilla#356]
# Bug Report

## Description
I added the deductions but the total shows only social insurance and the other 2 are not calculated.
![image](https://github.com/user-attachments/assets/4d17565f-42a8-485b-a155-29d8a4b59f91)
![image](https://github.com/user-attachments/assets/d721da29-4f5a-47a7-bf12-09c5e2a1abae)

**Comment by horilla-opensource** [comment]
Hi @loanduong02 ,
Can you please send the screenshot of the deduction form that you have set up?

With Regards,
**Team Horilla**

**Comment by loanduong02** [comment]
@horilla-opensource 
my deduction form
![image](https://github.com/user-attachments/assets/35e35a76-5f87-4568-ae3d-65383cd7a361)

**Comment by horilla-opensource** [comment]
Hi @loanduong02 ,
Sorry for the confusion. Can you please send the screenshot of the deduction form in edit mode?

**Comment by loanduong02** [comment]
@horilla-opensource 
![image](https://github.com/user-attachments/assets/a6e9294b-d6d3-4150-8162-bcce1f1106e6)

**Comment by horilla-opensource** [comment]
> # Bug Report
> ## Description
> I added the deductions but the total shows only social insurance and the other 2 are not calculated. ![image](https://private-user-images.githubusercontent.com/142495046/370972879-4d17565f-42a8-485b-a155-29d8a4b59f91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzQ1NTUsIm5iZiI6MTcyNzMzNDI1NSwicGF0aCI6Ii8xNDI0OTUwNDYvMzcwOTcyODc5LTRkMTc1NjVmLTQyYTgtNDg1Yi1hMTU1LTI5ZDhhNGI1OWY5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzA0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzNmMzI3MjZmOWFkYTA3NDg0M2Y2NGE3ZjM4YTQyNDc5YzU1NTI2NGIxMmYxZmVjYjk1MWNkYmY4YjgxZTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yGT5YZ-oKLdZaAxTNII-fqqFe39MdJgRjFrJqPJKlcE) ![image](https://private-user-images.githubusercontent.com/142495046/370972778-d721da29-4f5a-47a7-bf12-09c5e2a1abae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzQ1NTUsIm5iZiI6MTcyNzMzNDI1NSwicGF0aCI6Ii8xNDI0OTUwNDYvMzcwOTcyNzc4LWQ3MjFkYTI5LTRmNWEtNDdhNy1iZjEyLTA5YzVlMmExYWJhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzA0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYmNhYmJhZGU5Y2E2ZDZiOTQ0Y2RiMWRkODdlNDYxY2MwZGJmYjVkOGU2NDZiZTQ4ZmJlZmQ1NGNjN2FiYjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.x4Y6_nmLClXwNNFieGvVLfCNG2enk0ILTsu1QlQ3w-o)

Hi @loanduong02 ,

Can we confirm if the payroll is generated for the user Loan Duong Anh ?

With Regards,
**Team Horilla**

**Comment by loanduong02** [comment]
@horilla-opensource 
thanks u I found the solution by changing the options

**Comment by loanduong02** [comment]
@horilla-opensource 
when i create a deduction at number 1 in august but when i create payslip in september that deduction appears again and i dont want deduction number 2 to appear in september i think just create separate additional deduction for each month
![image](https://github.com/user-attachments/assets/087fff85-a220-49e2-a2d4-9492344c9354)
![image](https://github.com/user-attachments/assets/af32f9db-b613-4126-bf97-c67b4a7e7b8c)

**Comment by horilla-opensource** [comment]
Hi @loanduong02 ,

The fix has been committed to the master branch. Please pull the latest code and test it out.

With Regards,
**Team Horilla**

**Comment by loanduong02** [comment]
thanks @horilla-opensource  that problem has been solved
but when i choose NET PAY the values ​​do not change
![image](https://github.com/user-attachments/assets/6c1671ac-0f54-4e1f-850e-c4920b8b171a)
![image](https://github.com/user-attachments/assets/1accf8f1-2cc8-47ae-962e-30575f193a1a)
On the contrary, when I choose gross pay, the values ​​change.
![image](https://github.com/user-attachments/assets/15da2dde-bbd7-42c2-8644-21d2c7dcfad3)
![image](https://github.com/user-attachments/assets/9474bf6b-09e5-4c7d-8d54-ae104432747b)

**Comment by loanduong02** [comment]
hi @horilla-opensource do you have any way to solve this problem

**Comment by horilla-opensource** [comment]
Hi @loanduong02 ,
The solution is updated in the latest commit. Please check with the latest code.

**Comment by loanduong02** [comment]
hi @horilla-opensource 
This is the first payslip when I created it.
![image](https://github.com/user-attachments/assets/8c6de848-c777-4935-b44e-feb6f43a9f11)
I still don't see any change when I add deduction like video
https://github.com/user-attachments/assets/9130ef0b-06f5-46a1-b4dd-8d4b278676f2

**Comment by horilla-opensource** [comment]
Hi @loanduong02 ,
Can you try to create a fresh new payslip and confirm whether the issue is occurring in that also as we are not able to reproduce the issue at our end ?

**Comment by loanduong02** [comment]
hi @horilla-opensource 
I created a new payslip in October and added deductions to that payslip but still nothing changed
https://github.com/user-attachments/assets/2eedacb7-3b27-449a-9929-d93724d809bb

**Comment by horilla-opensource** [comment]
Hi @loanduong02 ,
Can you confirm whether your git head is the lastest head of the master branch of the repository?

**Comment by loanduong02** [comment]
hi @horilla-opensource  
I added the edits like what you changed in fix 356 in 2 files methods.py and component_views.py in payroll folder

**Comment by horilla-opensource** [comment]
Hi @loanduong02 ,
Can we connect on a call to discuss this?

With Regards,
**Team Horilla**

**Comment by loanduong02** [comment]
hi @horilla-opensource how can i contact. but my english communication is not good maybe only written communication

**Comment by loanduong02** [comment]
@horilla-opensource  Here is the description of the error which i hope you fix soon. thank you very much
https://github.com/user-attachments/assets/6262df3a-7f73-4d94-96aa-e9379f70cada

**Comment by horilla-opensource** [comment]
Hi @loanduong02 ,

From the screen recording you have shared, it seems that the code is not the latest code base fix we have added. Please pull the latest code and try again and let us know if it's still has issues.

With Regards,
**Team Horilla**

**Comment by loanduong02** [comment]
Hi @horilla-opensource 
![image](https://github.com/user-attachments/assets/3a3950d7-b9b0-43a9-81e5-37750b24b100)

**Comment by horilla-opensource** [comment]
Hi @loanduong02 ,

If the deductions are update compensation then those deductions wont be calculated to the total deductions.

**Comment by horilla-opensource** [comment]
Hi @loanduong02 ,
We are closing this issue due to inactivity. It seems that there hasn't been any recent activity or discussion, and we believe it may have been resolved or is no longer relevant. 
If you feel this issue is still important and should be addressed, please feel free to reopen it or create a new issue with updated details. 

With Regards,
**Team Horilla**
