### ISSUE TITLE
Employee template file importation Error

### ISSUE THREAD

**Issue by samthedevbrown** [horilla-opensource/horilla#472]
# Bug Report

## Description

Company detail and Bank Detail fields are not updated after employee template file is imported.

## Expected Behavior

After template is downloaded, correctly followed, and imported to add multiple employees to the system, all other occupied fields should be updated automatically(Company and Bank details) not Personal details fields only. Also import template should have bank details as tables/fields in the .xlsx template file.

## Environment

- **Django Version: Django version you're using, e.g., 3.2.1]_
- **Python Version: Python version, e.g., 3.9]_
- **Operating System: [Ubuntu 20.04]
- **Browser: Brave,, Firefox and opera browser]

**Comment by horilla-opensource** [comment]
Hi @samthedevbrown,,

Thanks for bringing this to our attention! 

Regarding the employee import process, currently, when importing employees, Personal details & Work details are being updated. We’re aware that bank details are not being included, and we plan to improve the employee import functionality to support these fields in the future.

In the meantime, please ensure that you have selected the **"All Company"** option in the navbar during the import process. This step is crucial to ensure that the import is linked to all companies in the system, and it will help with correct data handling.

As for the bank details, they are not yet included in the import template. We are actively working on adding these fields to the template, so the import process will be more complete moving forward.

Thank you for your patience, and we will keep you updated on the improvements.

Best regards,  
**Team Horilla**

**Comment by samthedevbrown** [comment]
Hello,
 
Any update on the employee Work details update because it becomes cumbersome if there about 100 employee Work details to imported and all these 100 employees need to be added to a different company manually.

When the preferred company in the navigation bar is selected, employee imports do not work which makes it necessary to manually edit employees and select the preferred company. This is a tedious process/task to do for over hundred employees.

Please help rectify this issue. Thank You.

Best regards,
Samthedevbrown

**Comment by JVKeller** [comment]
Same as #439

**Comment by horilla-opensource** [comment]
Hi everyone ,

https://github.com/user-attachments/assets/e0004dbe-0382-47ac-b2e3-ff5f70305e23

Refer to this video for bulk updating employee company instead of updating individually.  

Currently, we are converting Horilla HRMS to CBV. Once the conversion is complete, we will review the employee import method.  

Best Regards,  
**Team Horilla**

**Comment by JVKeller** [comment]
> Currently, we are converting Horilla HRMS to CBV.

What does this mean?

**Comment by horilla-opensource** [comment]
Hi @JVKeller,  

CBV stands for Class-Based Views. We are currently refactoring Horilla HRMS to use Class-Based Views instead of Function-Based Views, which will enhance code maintainability, scalability, and overall performance.  

Additionally, we have now fixed the issue with employee import. You can now import employees directly into a specific company instead of selecting "All Company" during import. This should make the process more efficient, especially when dealing with bulk employee uploads.  

Let us know if you encounter any further issues. Thanks for your patience and continued support!  

Best regards,
**Team Horilla**

**Comment by samthedevbrown** [comment]
Thank you for your response

**Comment by JVKeller** [comment]
Thank you for the explanation. 

Importing is still not working for me. I get a pop up that the import is successful, the error logs states the User with the email ID already exists and the employee is not showing in the employee-view.

There is a user created in the database, but it doesn't seem to map them to the employee-view correctly.

**Comment by horilla-opensource** [comment]
Hi @JVKeller ,

Please check employee view on `All Company` instance. 

Could you please share the Excel file you tried to import, without the email and phone number columns, so we can check it from our side?

Best Regards,
**Team Horilla**

**Comment by JVKeller** [comment]
For shits and giggles, I imported it as a csv and it worked...

Checked the logs and saw that my date format was off. I made it the same as the export template but it's not correct. It needs to be `YYYY-MM-DD`

Now it's importing more data with xlxs format. Everything but Job Role and Reporting Manager.




<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/JEFFKE~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/JEFFKE~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>


Badge   id | First Name | Last Name | Phone | Email | Gender | Department | Job Position | Job Role | Work Type | Shift | Employee Type | Reporting Manager | Company | Location | Date joining | Contract End Date | Basic Salary | Salary Hour
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
JAW-1018 | **** | **** | **** | ****@****.com | male | Driver | Truck Driver -   (Driver) | Shuttle Driver -   Truck Driver | Laborer | Day Shift | Hourly | **** **** (JAW0005) | JAW | JAW | 2012-12-27 |   |   |  



</body>

</html>

**Comment by horilla-opensource** [comment]
Hi @JVKeller ,

The values in the Job Role and Reporting Manager columns in your Excel sheet have some issues:

- The Job Role column should contain only the exact job role names as defined in the Job Role form. Please remove any additional text such as "-Truck Driver".
- ![Image](https://github.com/user-attachments/assets/8717823d-9e4f-40ca-a8af-d9f7d317230e)

- In the Reporting Manager column, please remove the Badge ID. It should only include the manager's First Name and Last Name.

**Comment by JVKeller** [comment]
> Hi [@JVKeller](https://github.com/JVKeller) ,
> 
> The values in the Job Role and Reporting Manager columns in your Excel sheet have some issues:
> 
>     * The Job Role column should contain only the exact job role names as defined in the Job Role form. Please remove any additional text such as "-Truck Driver".
> 
>     * ![Image](https://github.com/user-attachments/assets/8717823d-9e4f-40ca-a8af-d9f7d317230e)
> 
>     * In the Reporting Manager column, please remove the Badge ID. It should only include the manager's First Name and Last Name.

I'll try that and report back. I just copied the data that was in the export for those as well.

**Comment by horilla-opensource** [comment]
@JVKeller  Thanks for pointing that out! We'll update the export Excel file to ensure the data format is suitable for import—specifically for the Job Role and Reporting Manager columns. Appreciate your feedback!

**Comment by horilla-opensource** [comment]
Hi @JVKeller,

Thanks for your feedback!

We’ve updated the **employee import method** with a new function and improved workflow. Also, the **employee export file is now formatted to be suitable for re-import**, making the process smoother and more reliable.

Please pull the latest code.

Let us know if you face any issues with the new setup.

Best regards,  
**Team Horilla**

**Comment by JVKeller** [comment]
Testing this out today. 

The column order of the import template and a base export template don't align. I don't know if this is easy to change but might make someone happy :)

![Image](https://github.com/user-attachments/assets/8d65ea35-05fe-4351-8e07-76b725ec2ebc)

• Not able to update employee information with an import
• Getting a message that there was an error, but the error download is not being found
`"GET /employee/error-sheet-36a305af-1db5-4842-b89f-431eafbd5506 HTTP/1.0" 404 84605`

**Comment by horilla-opensource** [comment]
@JVKeller  Thanks for reporting this!

We've updated the source code to ensure that the column order in the Employee Import Excel now matches the Export Excel. This should help make the import/export workflow smoother and more intuitive.

Let us know if you encounter any further issues.
