### ISSUE TITLE
Deleting an an Employee Returns Error

### ISSUE THREAD

**Issue by wole001** [horilla-opensource/horilla#619]
Let's Say you create an employee. Upon Selecting Delete as seen below 

![Image](https://github.com/user-attachments/assets/21017472-d2fa-4a50-a209-c116a69c9959)

![Image](https://github.com/user-attachments/assets/4c8f8015-cdc2-49b4-aa54-21d8ce7d6d36)

It returns an Error

![Image](https://github.com/user-attachments/assets/6de2f88f-9259-477c-8d7f-b823422a61ac)

Dont know if the errors are related. 

But if you create an Employee. It generates Duplicate Contract Entries as seen Below

![Image](https://github.com/user-attachments/assets/bfa741fa-46bd-4cf8-90b1-5a9f3d531da8)

**Comment by iamawmrit** [comment]
@wole001 I did not encounter that error. It may have been resolved now!


<img width="965" alt="Image" src="https://github.com/user-attachments/assets/dacc0958-3514-46b0-b0bb-924b3ec08dd4" />

<img width="656" alt="Image" src="https://github.com/user-attachments/assets/c5bf5f4a-af24-4bbc-9342-964e77d62612" />

<img width="952" alt="Image" src="https://github.com/user-attachments/assets/26f646b7-eac0-480d-929e-b6889ff52ba1" />

**Comment by wole001** [comment]
Thanks @iamawmrit 

I have done a git pull as seen below 

![Image](https://github.com/user-attachments/assets/2a6d21b4-287c-4202-a66c-9d503f6249a3)

However when I try to delete still and still have the error

![Image](https://github.com/user-attachments/assets/3439f90e-16d6-416d-a960-f39b606e1f27)

**Comment by unreal0901** [comment]
can you run these commands and then check again
```python
python manage.py makemigrations
python manage.py migrate
```

**Comment by unreal0901** [comment]
@wole001 
when you pull new changes , model changes need to be applied .
so we use makemigrations to create change files
and then run migrate to apply those changes to the local database.

**Comment by wole001** [comment]
Oh I see. Thank you for your support

**Comment by wole001** [comment]
Any luck with the double entries with the Contract?

Thanks
